ARG ARCH=
FROM ${ARCH}python:3.10-slim

LABEL org.label-schema.maintainer="paul.schmidt@infologistix.de"
LABEL org.label-schema.build-date="05.11.2022"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.version="python3.10"

# install chromium
RUN apt update && apt install -y --no-install-recommends chromium chromium-driver
RUN apt autoclean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

COPY examples/ ./examples
